name: wakatime-stats

on:
  workflow_dispatch:
  schedule:
    - cron: '00 15 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: harry4455/waka-readme-stats@locale/korean
        with:
          WAKATIME_API_KEY: ae1ee393-1af5-4317-9ed1-ac041cb1e3cb
          GH_TOKEN: 913d7b7ef83937330bdc913c918c7fd0320f4ecd
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_SHORT_INFO: "True"
          LOCALE: "ko"
